# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190316_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tripType',
            field=models.CharField(default='Round', max_length=25),
        ),
    ]
