# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_triptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departureDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='returnDate',
            field=models.CharField(max_length=20),
        ),
    ]
